server.port=8082
spring.application.name=web

spring.redis.host=web-redis
spring.redis.port=6379
spring.redis.timeout=5000
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=4

user-core.base-url=http://user-core:8081

management.endpoints.web.exposure.include=health,info
management.endpoints.health.show-details=always
management.endpoint.health.probes.enabled=true
management.health.redis.enabled=true
management.health.db.enabled=true

logging.level.root=INFO
logging.level.org.springframework.web=INFO
logging.level.com.itgirl.web=DEBUG